CREATE TABLE luxury_housing (
    property_id VARCHAR(20) PRIMARY KEY,
    micro_market VARCHAR(100),
    project_name VARCHAR(200),
    developer_name VARCHAR(200),
    unit_size_sqft NUMERIC,
    configuration VARCHAR(20),
    ticket_price_cr NUMERIC,
    transaction_type VARCHAR(50),
    buyer_type VARCHAR(50),
    purchase_quarter DATE,
    connectivity_score NUMERIC,
    amenity_score NUMERIC,
    possession_status VARCHAR(50),
    sales_channel VARCHAR(100),
    nri_buyer VARCHAR(10),
    locality_infra_score NUMERIC,
    avg_traffic_time_min NUMERIC,
    buyer_comments TEXT,
    ticket_price_inr NUMERIC,
    price_per_sqft NUMERIC,
    quarter_number VARCHAR(20),
    booking_flag INT
);
